/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lti/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login Get */
        get: operations["login_get_lti_login_get"];
        put?: never;
        /** Login Post */
        post: operations["login_post_lti_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lti/launch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Launch */
        post: operations["launch_lti_launch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lti/jwks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jwks */
        get: operations["jwks_lti_jwks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Course */
        get: operations["get_course_courses__course_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Roster */
        get: operations["get_roster_courses__course_id__roster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Content */
        get: operations["get_content_courses__course_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assessments */
        get: operations["get_assessments_courses__course_id__assessments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}/skills/propose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Propose Course Skills
         * @description On-demand trigger for AI skill proposal, standalone, no relaunch
         *     needed. This was previously only ever fired as a side effect buried
         *     inside the LTI launch handler, meaning re-testing or re-running it
         *     required faking a fresh Blackboard launch each time. Same underlying
         *     pipeline (ai/skill_proposer.seed_course_skills), same idempotency
         *     behavior: if this course already has any skill rows, approved or
         *     proposed, this is a no-op, delete them first (in Supabase) if you
         *     genuinely want a from-scratch re-proposal, e.g. after fixing a bug in
         *     the proposal logic itself, or want to re-run against changed course
         *     content.
         */
        post: operations["propose_course_skills_courses__course_id__skills_propose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Course */
        post: operations["ingest_course_courses__course_id__ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Modules
         * @description Distinct modules detected for this course from the last ingest run,
         *     with content and skill counts. Generic over however this institution's
         *     Blackboard course is actually organized, no naming assumed. Useful for
         *     an admin screen to sanity-check ingest, and as the source of options for
         *     any future module-scoped filtering in the UI.
         */
        get: operations["list_modules_courses__course_id__modules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}/assessments/{column_id}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Post Grade */
        patch: operations["post_grade_courses__course_id__assessments__column_id__grade_patch"];
        trace?: never;
    };
    "/courses/{course_id}/diagnostic/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Diagnostic Status
         * @description Lightweight due-check for a notification badge. No generation
         *     happens here, just skill + evidence reads, so this is safe to poll from
         *     the workspace home or the sidebar without generating anything. The
         *     diagnostic should not sit open as a permanent default tab; it should
         *     surface only when there is something new for THIS student to baseline.
         */
        get: operations["get_diagnostic_status_courses__course_id__diagnostic_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}/diagnostic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Diagnostic */
        get: operations["get_diagnostic_courses__course_id__diagnostic_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}/diagnostic/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Diagnostic */
        post: operations["submit_diagnostic_courses__course_id__diagnostic_submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice/{course_id}/next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Next Item */
        get: operations["next_item_practice__course_id__next_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice/{course_id}/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Set
         * @description Generate a batch of practice items for ONE skill and group them under a
         *     quiz_sets row. This is the batch replacement for calling /next N times.
         *
         *     The set row is created FIRST (status-free — it's just a grouping) so each
         *     generate_question call can write its set_id at insert time; an item is
         *     therefore never briefly persisted outside the set it belongs to. If every
         *     generation call fails, the empty set row is cleaned up rather than left as
         *     a dangling grouping with no items.
         *
         *     A POST, not a GET: this has a side effect (persists N items), so it must
         *     not be cached or prefetched like the read-shaped /next is.
         */
        post: operations["create_set_practice__course_id__set_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/practice/{course_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit */
        post: operations["submit_practice__course_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flashcards/{course_id}/deck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deck
         * @description The review queue: due scheduled cards first, topped up with fresh cards
         *     for skills the student hasn't started. Answer keys never leave the server.
         *     `skill_id` is the topic picker's explicit override — when set, the whole
         *     deck (due cards AND fresh top-up) scopes to that one skill instead of the
         *     course-wide due-first mix, same "auto vs chosen" pattern as practice.
         */
        get: operations["deck_flashcards__course_id__deck_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/flashcards/{course_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review
         * @description Self-mark one study card and advance its spaced-repetition schedule.
         *
         *     Study mode is memorization, not assessment: the student flips the card,
         *     sees the answer, and marks "Got it" or "Review again" themselves. There is
         *     no server grading here — `remembered` is the student's own call, by design.
         *
         *     What that means for the twin: this writes an evidence_event (type
         *     'flashcard', correct=remembered) but does NOT call tracer.apply_evidence,
         *     so mastery_state never moves on self-report. That row is still written on
         *     purpose — the research export (0003_research.sql) aggregates flashcard
         *     evidence into research_evidence_anon / research_cohort_daily, and dropping
         *     it would make every self-paced study session invisible to that pipeline.
         *     Mastery is fed by diagnostic, quiz (test mode), and tutor checks only; the
         *     study -> test bridge is what routes studying into a real mastery signal.
         *     XP still moves off study because xp.summary reads evidence_events, which is
         *     the intended behavior (reward the work, don't inflate mastery).
         */
        post: operations["review_flashcards__course_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{course_id}/skill/{skill_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Lesson
         * @description Load the skill's guided lesson, generating and persisting it on first
         *     request. Idempotent thereafter.
         */
        get: operations["get_lesson_lessons__course_id__skill__skill_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/lessons/{course_id}/steps/{step_id}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Check
         * @description Grade a step's comprehension check server-side. The step advances (the
         *     read -> understand -> apply gate) only when the client sees correct=True.
         *     A pass writes a tutor evidence_event and moves the tracer; the schedule is
         *     seeded too so a checked concept enters spaced review like any other card.
         *
         *     Ownership is verified in two independent steps before anything is
         *     written, because the URL's course_id is caller-supplied and must not be
         *     trusted on its own:
         *       1. the step -> its lesson_id (a step id + check_item_id is not, by
         *          itself, proof the step belongs to THIS course);
         *       2. that lesson_id -> its lesson row, filtered by course_id AND
         *          institution_id from the path. Only then is the step known to
         *          actually belong here, closing the hole where a client could submit
         *          /lessons/COURSE_B/steps/{step-from-course-A}/check and have
         *          evidence + mastery written against COURSE_B using a check item that
         *          was never generated for it.
         */
        post: operations["submit_check_lessons__course_id__steps__step_id__check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tutor/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_tutor_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_tutor_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tutor/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_tutor_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_tutor_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tutor/conversations/{conversation_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Attachment */
        post: operations["upload_attachment_tutor_conversations__conversation_id__attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tutor/conversations/{conversation_id}/attachments/{attachment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Attachment */
        delete: operations["delete_attachment_tutor_conversations__conversation_id__attachments__attachment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tutor/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask */
        post: operations["ask_tutor_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}/twin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Twin */
        get: operations["get_twin_courses__course_id__twin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}/next-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Next Up
         * @description One recommendation: the skill this student should practice next.
         *     Lightweight — reuses the same weakest-skill picker as practice but does
         *     not generate an item (that happens when they actually start).
         */
        get: operations["next_up_courses__course_id__next_up_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{course_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Learning Plan
         * @description What this learner's instructor has actually assigned them.
         *
         *     The closing half of the human-in-the-loop loop. The instructor surface
         *     generates AI recommendations and decides on them; this endpoint is the
         *     only way a decided action reaches the learner. It filters on
         *     status in ('approved','modified') by design:
         *
         *       suggested  -> the teacher has not looked yet. Invisible here. If a
         *                     learner could see un-decided AI output, the gate would
         *                     be decorative.
         *       rejected   -> the teacher declined it. Invisible here, kept in the
         *                     audit trail.
         *       completed  -> done, shown greyed so the learner can see their history.
         *
         *     The learner sees the action and the instructor's note, never the
         *     model's confidence score or the raw evidence panel — those are
         *     instructor-facing framing about the learner, and handing a student
         *     "the model is 84% confident you are weak at IAM" is the exact thing
         *     the design brief rules out.
         */
        get: operations["learning_plan_courses__course_id__plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/{course_id}/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Heatmap */
        get: operations["heatmap_dashboard__course_id__heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/{course_id}/at-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** At Risk */
        get: operations["at_risk_dashboard__course_id__at_risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/{course_id}/students/{user_id}/twin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Student Twin */
        get: operations["student_twin_dashboard__course_id__students__user_id__twin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/{course_id}/skills/proposed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Proposed Skills
         * @description Skills awaiting review for this course, with any 'possible duplicate'
         *     hint the proposer attached. Feeds the review UI (or read straight in
         *     Supabase for the demo).
         */
        get: operations["list_proposed_skills_dashboard__course_id__skills_proposed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/{course_id}/skills/auto-matched": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Auto Matched Skills
         * @description Skills that were auto-approved by cross-course match (they resembled a
         *     skill already approved in another course, above the AUTO_MATCH bar, so
         *     they went live without individual review, that's the scaling win).
         *
         *     Surfacing them here is the auditability half of that trade: an instructor
         *     can SEE which of their live skills were inherited from elsewhere
         *     (canonical_skill_id is set, and proposed_source records what it matched),
         *     rather than the reuse being invisible. If an inherited skill's wording
         *     isn't quite right for THIS course, the detach endpoint below turns it
         *     back into a course-local proposed skill they can fine-tune.
         */
        get: operations["list_auto_matched_skills_dashboard__course_id__skills_auto_matched_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/{course_id}/skills/{skill_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Review Proposed Skill
         * @description Approve or reject a proposed skill, with optional inline edits. Only
         *     after approval does the skill feed the learner/instructor surfaces.
         */
        patch: operations["review_proposed_skill_dashboard__course_id__skills__skill_id__review_patch"];
        trace?: never;
    };
    "/dashboard/{course_id}/skills/{skill_id}/detach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Detach Auto Matched Skill
         * @description Turn an auto-matched skill back into a course-local skill for review.
         *
         *     This is the reversibility half of cross-course auto-match: reuse is a
         *     default, not a lock-in. When an instructor decides an inherited skill's
         *     wording (or Bloom level, or weight) needs to be tuned specifically for
         *     THIS course, detaching clears canonical_skill_id and sends the row back
         *     to 'proposed', so it re-enters the normal review flow where they can edit
         *     it freely. It stops feeding the learner surfaces until re-approved (same
         *     as any proposed skill), which is the correct, conservative behavior, a
         *     skill mid-edit shouldn't be live.
         *
         *     Only affects rows that were actually auto-matched (canonical_skill_id set
         *     and status approved); a 404 otherwise.
         */
        patch: operations["detach_auto_matched_skill_dashboard__course_id__skills__skill_id__detach_patch"];
        trace?: never;
    };
    "/dashboard/{course_id}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Course Roster
         * @description One row per enrolled STUDENT, with real names.
         *
         *     Two things worth stating because both were bugs:
         *
         *     Students only. cohort.student_ids requires role='student' on BOTH the
         *     enrollment and the user, so a co-teacher or an admin who launched the
         *     course never lands in the roster as a learner with 0% mastery.
         *
         *     Real names. The instructor is the teacher of record and already holds
         *     this roster in their gradebook; a class list of 'anon-8f2c1b' is not a
         *     privacy win, it is an unusable screen that gets worked around. The
         *     de-identification rule (CLAUDE.md 4) governs what leaves for a model or
         *     a researcher, and it still holds: every row carries its pseudonym, the
         *     UI can flip to pseudonyms for screen-sharing, and ai/prescriber.py is
         *     handed the pseudonym and never the name.
         */
        get: operations["course_roster_dashboard__course_id__roster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/{course_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Course Stats
         * @description Cohort KPI strip plus the series behind every chart on the overview:
         *     readiness trend (from the worker's snapshots, real history), daily
         *     evidence volume, mastery band distribution, Bloom's coverage, per-skill
         *     breakdown weakest-first, and the human-in-the-loop decision counts.
         */
        get: operations["course_stats_dashboard__course_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/{course_id}/students/{user_id}/record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Student Record
         * @description The teacher-facing read of one learner.
         *
         *     Deliberately not the student's twin payload. The twin answers "how am I
         *     doing"; this answers "what does this learner need next, and what will I
         *     do about it" — so it adds identity, standing against the cohort,
         *     momentum (last 10 graded vs the 10 before), engagement pattern, and the
         *     readiness history the trend line is drawn from.
         */
        get: operations["student_record_dashboard__course_id__students__user_id__record_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/{course_id}/students/{user_id}/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recommendations
         * @description Every recommendation for this learner, decided or not. Rejected rows
         *     stay in the list rather than disappearing: the decision history IS the
         *     human-in-the-loop record, and a teacher should be able to see they
         *     already turned something down.
         */
        get: operations["list_recommendations_dashboard__course_id__students__user_id__recommendations_get"];
        put?: never;
        /**
         * Generate Recommendations
         * @description Ask Kala for next actions for this learner.
         *
         *     De-identified before the call (the prescriber receives the pseudonym and
         *     numbers, never a name), persisted as status='suggested', and invisible
         *     to the learner until a teacher decides. Any pending suggestions from a
         *     previous run are superseded so the queue does not accumulate stale
         *     duplicates every time the teacher hits refresh — decided rows are never
         *     touched, because they are the audit trail.
         */
        post: operations["generate_recommendations_dashboard__course_id__students__user_id__recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/{course_id}/recommendations/{rec_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Decide Recommendation
         * @description Approve, modify, or reject one recommendation. This is the gate.
         *
         *     'modified' is kept distinct from 'approved' rather than folded into it:
         *     "how often does a teacher edit the AI instead of taking it as written"
         *     is one of the study's actual research questions, and it is only
         *     answerable if the two decisions are different values in the column.
         */
        patch: operations["decide_recommendation_dashboard__course_id__recommendations__rec_id__patch"];
        trace?: never;
    };
    "/dashboard/{course_id}/students/{user_id}/interventions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Intervention
         * @description The teacher's own move. Lands in the learner's plan immediately with
         *     status='approved' and source='instructor' — a human wrote it, so there
         *     is nothing to gate. The symmetry matters: the same object carries both
         *     an AI proposal a teacher accepted and an action a teacher authored, so
         *     the learner's plan is one list and the audit trail shows which is
         *     which.
         */
        post: operations["create_intervention_dashboard__course_id__students__user_id__interventions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gamification/{course_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summary */
        get: operations["summary_gamification__course_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Ask */
        Ask: {
            /** Course Id */
            course_id: string;
            /** Question */
            question: string;
            /**
             * Style
             * @default default
             * @enum {string}
             */
            style: "default" | "eli5" | "detail";
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /** Body_launch_lti_launch_post */
        Body_launch_lti_launch_post: {
            /** Id Token */
            id_token: string;
            /** State */
            state: string;
        };
        /** Body_upload_attachment_tutor_conversations__conversation_id__attachments_post */
        Body_upload_attachment_tutor_conversations__conversation_id__attachments_post: {
            /** File */
            file: string;
        };
        /** CheckBody */
        CheckBody: {
            /** Item Id */
            item_id: string;
            /** Choice Id */
            choice_id: string;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /**
             * Hints Used
             * @default 0
             */
            hints_used: number;
        };
        /** CreateConversation */
        CreateConversation: {
            /** Course Id */
            course_id: string;
            /** Skill Id */
            skill_id?: string | null;
        };
        /** GradeBody */
        GradeBody: {
            /** User Id */
            user_id: string;
            /** Score */
            score: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InterventionCreate
         * @description A teacher writing their own action, not editing one Kala proposed.
         */
        InterventionCreate: {
            /** Title */
            title: string;
            /**
             * Kind
             * @default practice
             */
            kind: string;
            /**
             * Priority
             * @default medium
             */
            priority: string;
            /** Skill Id */
            skill_id?: string | null;
            /** Instructor Note */
            instructor_note?: string | null;
        };
        /** RecommendationDecision */
        RecommendationDecision: {
            /** Status */
            status: string;
            /** Title */
            title?: string | null;
            /** Kind */
            kind?: string | null;
            /** Priority */
            priority?: string | null;
            /** Decision Note */
            decision_note?: string | null;
            /** Instructor Note */
            instructor_note?: string | null;
        };
        /** ReviewBody */
        ReviewBody: {
            /** Item Id */
            item_id: string;
            /** Remembered */
            remembered: boolean;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
        };
        /** ReviewDecision */
        ReviewDecision: {
            /** Status */
            status: string;
            /** Name */
            name?: string | null;
            /** Bloom Level */
            bloom_level?: string | null;
            /** Blueprint Weight */
            blueprint_weight?: number | null;
        };
        /** SubmitAnswer */
        SubmitAnswer: {
            /** Item Id */
            item_id: string;
            /** Choice Id */
            choice_id: string;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** SubmitBody */
        app__routers__diagnostic__SubmitBody: {
            /** Answers */
            answers: components["schemas"]["SubmitAnswer"][];
        };
        /** SubmitBody */
        app__routers__practice__SubmitBody: {
            /** Item Id */
            item_id: string;
            /** Choice Id */
            choice_id: string;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_get_lti_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_post_lti_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    launch_lti_launch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_launch_lti_launch_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jwks_lti_jwks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_course_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_roster_courses__course_id__roster_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_content_courses__course_id__content_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assessments_courses__course_id__assessments_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_course_skills_courses__course_id__skills_propose_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_course_courses__course_id__ingest_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_modules_courses__course_id__modules_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_grade_courses__course_id__assessments__column_id__grade_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
                column_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diagnostic_status_courses__course_id__diagnostic_status_get: {
        parameters: {
            query?: {
                module_ref?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_diagnostic_courses__course_id__diagnostic_get: {
        parameters: {
            query?: {
                module_ref?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_diagnostic_courses__course_id__diagnostic_submit_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__routers__diagnostic__SubmitBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    next_item_practice__course_id__next_get: {
        parameters: {
            query?: {
                skill_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_set_practice__course_id__set_post: {
        parameters: {
            query?: {
                skill_id?: string | null;
                size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_practice__course_id__submit_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__routers__practice__SubmitBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deck_flashcards__course_id__deck_get: {
        parameters: {
            query?: {
                limit?: number;
                module_ref?: string | null;
                skill_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_flashcards__course_id__review_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_lesson_lessons__course_id__skill__skill_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_check_lessons__course_id__steps__step_id__check_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
                step_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_tutor_conversations_get: {
        parameters: {
            query: {
                course_id: string;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_tutor_conversations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversation"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_tutor_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_tutor_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_attachment_tutor_conversations__conversation_id__attachments_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_attachment_tutor_conversations__conversation_id__attachments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_attachment_tutor_conversations__conversation_id__attachments__attachment_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
                attachment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_tutor_ask_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Ask"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_twin_courses__course_id__twin_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    next_up_courses__course_id__next_up_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    learning_plan_courses__course_id__plan_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heatmap_dashboard__course_id__heatmap_get: {
        parameters: {
            query?: {
                module_ref?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    at_risk_dashboard__course_id__at_risk_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    student_twin_dashboard__course_id__students__user_id__twin_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proposed_skills_dashboard__course_id__skills_proposed_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_auto_matched_skills_dashboard__course_id__skills_auto_matched_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_proposed_skill_dashboard__course_id__skills__skill_id__review_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detach_auto_matched_skill_dashboard__course_id__skills__skill_id__detach_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
                skill_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_roster_dashboard__course_id__roster_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    course_stats_dashboard__course_id__stats_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    student_record_dashboard__course_id__students__user_id__record_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recommendations_dashboard__course_id__students__user_id__recommendations_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_recommendations_dashboard__course_id__students__user_id__recommendations_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_recommendation_dashboard__course_id__recommendations__rec_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
                rec_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_intervention_dashboard__course_id__students__user_id__interventions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterventionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summary_gamification__course_id__summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
