/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ClassRouteImport } from './routes/class';
import { Route as CourseRouteImport } from './routes/course';
import { Route as LaunchRouteImport } from './routes/launch';
import { Route as SessionExpiredRouteImport } from './routes/session-expired';
import { Route as UnauthorizedRouteImport } from './routes/unauthorized';
import { Route as ClassIndexRouteImport } from './routes/class/index';
import { Route as CourseIndexRouteImport } from './routes/course/index';
import { Route as CourseDiagnosticRouteImport } from './routes/course/diagnostic';
import { Route as CourseFlashcardsRouteImport } from './routes/course/flashcards';
import { Route as CoursePracticeRouteImport } from './routes/course/practice';
import { Route as CourseTutorRouteImport } from './routes/course/tutor';
import { Route as CourseTwinRouteImport } from './routes/course/twin';
import { Route as ClassStudentUidRouteImport } from './routes/class/student.$uid';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ClassRoute = ClassRouteImport.update({
  id: '/class',
  path: '/class',
  getParentRoute: () => rootRouteImport,
} as any);
const CourseRoute = CourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => rootRouteImport,
} as any);
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any);
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any);
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any);
const ClassIndexRoute = ClassIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClassRoute,
} as any);
const CourseIndexRoute = CourseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CourseRoute,
} as any);
const CourseDiagnosticRoute = CourseDiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => CourseRoute,
} as any);
const CourseFlashcardsRoute = CourseFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => CourseRoute,
} as any);
const CoursePracticeRoute = CoursePracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => CourseRoute,
} as any);
const CourseTutorRoute = CourseTutorRouteImport.update({
  id: '/tutor',
  path: '/tutor',
  getParentRoute: () => CourseRoute,
} as any);
const CourseTwinRoute = CourseTwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => CourseRoute,
} as any);
const ClassStudentUidRoute = ClassStudentUidRouteImport.update({
  id: '/student/$uid',
  path: '/student/$uid',
  getParentRoute: () => ClassRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/class': typeof ClassRouteWithChildren;
  '/course': typeof CourseRouteWithChildren;
  '/launch': typeof LaunchRoute;
  '/session-expired': typeof SessionExpiredRoute;
  '/unauthorized': typeof UnauthorizedRoute;
  '/course/diagnostic': typeof CourseDiagnosticRoute;
  '/course/flashcards': typeof CourseFlashcardsRoute;
  '/course/practice': typeof CoursePracticeRoute;
  '/course/tutor': typeof CourseTutorRoute;
  '/course/twin': typeof CourseTwinRoute;
  '/class/': typeof ClassIndexRoute;
  '/course/': typeof CourseIndexRoute;
  '/class/student/$uid': typeof ClassStudentUidRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/launch': typeof LaunchRoute;
  '/session-expired': typeof SessionExpiredRoute;
  '/unauthorized': typeof UnauthorizedRoute;
  '/course/diagnostic': typeof CourseDiagnosticRoute;
  '/course/flashcards': typeof CourseFlashcardsRoute;
  '/course/practice': typeof CoursePracticeRoute;
  '/course/tutor': typeof CourseTutorRoute;
  '/course/twin': typeof CourseTwinRoute;
  '/class': typeof ClassIndexRoute;
  '/course': typeof CourseIndexRoute;
  '/class/student/$uid': typeof ClassStudentUidRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/class': typeof ClassRouteWithChildren;
  '/course': typeof CourseRouteWithChildren;
  '/launch': typeof LaunchRoute;
  '/session-expired': typeof SessionExpiredRoute;
  '/unauthorized': typeof UnauthorizedRoute;
  '/course/diagnostic': typeof CourseDiagnosticRoute;
  '/course/flashcards': typeof CourseFlashcardsRoute;
  '/course/practice': typeof CoursePracticeRoute;
  '/course/tutor': typeof CourseTutorRoute;
  '/course/twin': typeof CourseTwinRoute;
  '/class/': typeof ClassIndexRoute;
  '/course/': typeof CourseIndexRoute;
  '/class/student/$uid': typeof ClassStudentUidRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/class'
    | '/course'
    | '/launch'
    | '/session-expired'
    | '/unauthorized'
    | '/course/diagnostic'
    | '/course/flashcards'
    | '/course/practice'
    | '/course/tutor'
    | '/course/twin'
    | '/class/'
    | '/course/'
    | '/class/student/$uid';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/launch'
    | '/session-expired'
    | '/unauthorized'
    | '/course/diagnostic'
    | '/course/flashcards'
    | '/course/practice'
    | '/course/tutor'
    | '/course/twin'
    | '/class'
    | '/course'
    | '/class/student/$uid';
  id:
    | '__root__'
    | '/'
    | '/class'
    | '/course'
    | '/launch'
    | '/session-expired'
    | '/unauthorized'
    | '/course/diagnostic'
    | '/course/flashcards'
    | '/course/practice'
    | '/course/tutor'
    | '/course/twin'
    | '/class/'
    | '/course/'
    | '/class/student/$uid';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ClassRoute: typeof ClassRouteWithChildren;
  CourseRoute: typeof CourseRouteWithChildren;
  LaunchRoute: typeof LaunchRoute;
  SessionExpiredRoute: typeof SessionExpiredRoute;
  UnauthorizedRoute: typeof UnauthorizedRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/class': {
      id: '/class';
      path: '/class';
      fullPath: '/class';
      preLoaderRoute: typeof ClassRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/course': {
      id: '/course';
      path: '/course';
      fullPath: '/course';
      preLoaderRoute: typeof CourseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/launch': {
      id: '/launch';
      path: '/launch';
      fullPath: '/launch';
      preLoaderRoute: typeof LaunchRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/session-expired': {
      id: '/session-expired';
      path: '/session-expired';
      fullPath: '/session-expired';
      preLoaderRoute: typeof SessionExpiredRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/unauthorized': {
      id: '/unauthorized';
      path: '/unauthorized';
      fullPath: '/unauthorized';
      preLoaderRoute: typeof UnauthorizedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/class/': {
      id: '/class/';
      path: '/';
      fullPath: '/class/';
      preLoaderRoute: typeof ClassIndexRouteImport;
      parentRoute: typeof ClassRoute;
    };
    '/course/': {
      id: '/course/';
      path: '/';
      fullPath: '/course/';
      preLoaderRoute: typeof CourseIndexRouteImport;
      parentRoute: typeof CourseRoute;
    };
    '/course/diagnostic': {
      id: '/course/diagnostic';
      path: '/diagnostic';
      fullPath: '/course/diagnostic';
      preLoaderRoute: typeof CourseDiagnosticRouteImport;
      parentRoute: typeof CourseRoute;
    };
    '/course/flashcards': {
      id: '/course/flashcards';
      path: '/flashcards';
      fullPath: '/course/flashcards';
      preLoaderRoute: typeof CourseFlashcardsRouteImport;
      parentRoute: typeof CourseRoute;
    };
    '/course/practice': {
      id: '/course/practice';
      path: '/practice';
      fullPath: '/course/practice';
      preLoaderRoute: typeof CoursePracticeRouteImport;
      parentRoute: typeof CourseRoute;
    };
    '/course/tutor': {
      id: '/course/tutor';
      path: '/tutor';
      fullPath: '/course/tutor';
      preLoaderRoute: typeof CourseTutorRouteImport;
      parentRoute: typeof CourseRoute;
    };
    '/course/twin': {
      id: '/course/twin';
      path: '/twin';
      fullPath: '/course/twin';
      preLoaderRoute: typeof CourseTwinRouteImport;
      parentRoute: typeof CourseRoute;
    };
    '/class/student/$uid': {
      id: '/class/student/$uid';
      path: '/student/$uid';
      fullPath: '/class/student/$uid';
      preLoaderRoute: typeof ClassStudentUidRouteImport;
      parentRoute: typeof ClassRoute;
    };
  }
}

interface ClassRouteChildren {
  ClassIndexRoute: typeof ClassIndexRoute;
  ClassStudentUidRoute: typeof ClassStudentUidRoute;
}

const ClassRouteChildren: ClassRouteChildren = {
  ClassIndexRoute: ClassIndexRoute,
  ClassStudentUidRoute: ClassStudentUidRoute,
};

const ClassRouteWithChildren = ClassRoute._addFileChildren(ClassRouteChildren);

interface CourseRouteChildren {
  CourseDiagnosticRoute: typeof CourseDiagnosticRoute;
  CourseFlashcardsRoute: typeof CourseFlashcardsRoute;
  CoursePracticeRoute: typeof CoursePracticeRoute;
  CourseTutorRoute: typeof CourseTutorRoute;
  CourseTwinRoute: typeof CourseTwinRoute;
  CourseIndexRoute: typeof CourseIndexRoute;
}

const CourseRouteChildren: CourseRouteChildren = {
  CourseDiagnosticRoute: CourseDiagnosticRoute,
  CourseFlashcardsRoute: CourseFlashcardsRoute,
  CoursePracticeRoute: CoursePracticeRoute,
  CourseTutorRoute: CourseTutorRoute,
  CourseTwinRoute: CourseTwinRoute,
  CourseIndexRoute: CourseIndexRoute,
};

const CourseRouteWithChildren =
  CourseRoute._addFileChildren(CourseRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassRoute: ClassRouteWithChildren,
  CourseRoute: CourseRouteWithChildren,
  LaunchRoute: LaunchRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  UnauthorizedRoute: UnauthorizedRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
