"""The LMS connector interface. One interface, per-LMS implementations, so the
rest of the backend is LMS-agnostic. Blackboard is the pilot; Canvas is a stub."""
from __future__ import annotations

from typing import Protocol


class LMSConnector(Protocol):
    def get_roster(self, course_ref: str) -> list[dict]: ...
    def get_content(self, course_ref: str) -> list[dict]: ...
    def get_grades(self, course_ref: str) -> list[dict]: ...
    def post_grade(self, course_ref: str, user_ref: str, score: float) -> None: ...
