"""The LMS connector interface. One interface, per-LMS implementations, so the
rest of the backend is LMS-agnostic. Blackboard is the pilot; Canvas is a stub."""
from __future__ import annotations

from typing import Protocol


class LMSConnector(Protocol):
    def resolve_course_ref(self, external_id: str) -> str: ...
    def get_roster(self, course_ref: str) -> list[dict]: ...
    def get_content(self, course_ref: str) -> list[dict]: ...
    def get_assessments(self, course_ref: str) -> list[dict]: ...
    def post_grade(self, course_ref: str, column_id: str, user_ref: str, score: float) -> None: ...
